name: CI

on:
  push:
  pull_request:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.85.0
          components: rustfmt, clippy
      - name: Format
        run: cargo fmt --all -- --check
      - name: Test
        run: cargo test --locked
      - name: Clippy
        run: cargo clippy --all-targets --locked -- -D warnings
